# Border size in pixels (default: 2.0)
border_size = 5.0

[keymaps]
"cmd+0" = ["focus workspace 0"]
"cmd+1" = ["focus workspace 1"]
"cmd+2" = ["focus workspace 2"]
"cmd+3" = ["focus workspace 3"]
"cmd+4" = ["focus workspace 4"]
"cmd+5" = ["focus workspace 5"]
"cmd+6" = ["focus workspace 6"]
"cmd+7" = ["focus workspace 7"]
"cmd+8" = ["focus workspace 8"]
"cmd+9" = ["focus workspace 9"]
"cmd+e" = ["toggle direction"]
"cmd+p" = ["focus parent"]
"cmd+h" = ["focus left"]
"cmd+j" = ["focus down"]
"cmd+k" = ["focus up"]
"cmd+l" = ["focus right"]
